import { Injectable, signal } from '@angular/core';

export type Language = 'FR' | 'EN';

type Translations = {
    [key: string]: string;
};

@Injectable({
    providedIn: 'root'
})
export class LanguageService {
    currentLang = signal<Language>('FR');

    private translations: { FR: Translations; EN: Translations } = {
        FR: {
            'sidebar.dashboard': 'Dashboard',
            'sidebar.dashboardAdmin': 'Tableau de bord Admin',
            'sidebar.dashboardStudy': 'Tableau de bord Études',
            'sidebar.users': 'Utilisateurs',
            'sidebar.subscriptions': 'Plans d\'abonnement',
            'sidebar.subcontractors': 'Sous-traitants',
            'sidebar.suppliers': 'Fournisseurs',
            'sidebar.settings': 'Paramètres',
            'sidebar.unitMeasure': 'Unités de mesure',
            'sidebar.documents': 'Documents',
            'sidebar.propertyType': 'Types de propriété',
            'sidebar.materialCategories': 'Catégories de matériaux',
            'sidebar.projects': 'Projets',
            'sidebar.requests': 'Demandes',
            'sidebar.orders': 'Commandes',
            'sidebar.myAccount': 'Mon compte',
            'sidebar.logout': 'Déconnexion',
            'sidebar.reclamations': 'Réclamations',
            'breadcrumb.helpSupport': 'Aide & Support',
            'breadcrumb.language': 'Langue',
            'breadcrumb.home': 'Accueil',
            'breadcrumb.dashboard': 'Tableau de bord',
            'profile.siteManager': 'Manager',
            'profile.subcontractor': 'Sous-traitant',
            'profile.supplier': 'Fournisseur',
            'profile.admin': 'Administrateur',
            'profile.bet': 'Bureau d\'études',
            'profile.user': 'Utilisateur',
            'profile.promoter': 'Promoteur',
            'profile.moa': 'Maître d\'ouvrage',
            'profile.notaire': 'Notaire',
            'profile.reservataire': 'Réservataire',
            'profile.bank': 'Banque',
            'profile.agency': 'Agence',
            'profile.proprietaire': 'Propriétaire',
            'profile.syndic': 'Syndic',
            'profile.locataire': 'Locataire',
            'profile.prestataire': 'Prestataire',
            'profile.tom': 'TOM',
            'profile.worker': 'Ouvrier',
            'common.search': 'Rechercher',
            'common.searchPlaceholder': 'Rechercher...',
            'common.filter': 'Filtres',
            'common.export': 'Exporter',
            'common.add': 'Ajouter',
            'common.edit': 'Modifier',
            'common.delete': 'Supprimer',
            'common.save': 'Enregistrer', // Unique key
            'common.cancel': 'Annuler',
            'common.close': 'Fermer',
            'common.next': 'Suivant',
            'common.previous': 'Précédent',
            'common.loading': 'Chargement...',
            'common.noData': 'Aucune donnée disponible',
            'common.actions': 'Actions',
            'common.status': 'Statut',
            'common.date': 'Date',
            'common.view': 'Voir',
            'common.copy': 'Copier',
            'common.confirm': 'Confirmer',
            'common.yes': 'Oui',
            'common.no': 'Non',
            'common.active': 'Actif',
            'common.inactive': 'Inactif',
            'common.all': 'Tous',
            'common.create': 'Créer',
            'common.update': 'Mettre à jour',
            'common.download': 'Télécharger',
            'common.upload': 'Téléverser',
            'common.back': 'Retour',
            'common.details': 'Détails',
            'common.total': 'Total',
            'common.showing': 'Affichage de',
            'common.to': 'à',
            'common.of': 'sur',
            'common.results': 'résultats',
            'notifications.title': 'Notifications',
            'notifications.newUser': 'Nouvel utilisateur inscrit',
            'notifications.newUserMessage': '{{name}} vient de s\'inscrire',
            'notifications.noNotifications': 'Aucune notification',
            'notifications.markAllRead': 'Tout marquer comme lu',
            'dashboard.title': 'Tableau de bord',
            'dashboard.overview': 'Vue d\'ensemble des chantiers',
            'status.inProgress': 'En cours',
            'status.delayed': 'En retard',
            'status.pending': 'En attente',
            'status.completed': 'Terminé',
            'users.title': 'Gestion des utilisateurs',
            'help.title': 'Aide & Support',
            'help.description': 'Contactez-nous pour toute question ou assistance. Nous sommes là pour vous aider !',
            'help.email': 'Email',
            'help.phone': 'Téléphone',
            'help.hours': 'Heures de support :',
            'help.hoursValue': 'Lundi - Vendredi, 08h00 - 18h00',

            // Compte
            'compte.title': 'Mon compte',
            'compte.tabs.info': 'Informations personnelles',
            'compte.tabs.subscriptions': 'Abonnements',
            'compte.tabs.invoices': 'Factures',
            'compte.form.firstName': 'Prénom',
            'compte.form.lastName': 'Nom',
            'compte.form.phone': 'Numéro de téléphone',
            'compte.form.email': 'Email',
            'compte.form.address': 'Adresse',
            'compte.form.company': 'Nom de l\'entreprise',
            'compte.form.profile': 'Profil',
            'compte.profile.cantEdit': 'Le profil ne peut pas être modifié',
            'compte.photo.new': 'Nouvelle photo',
            'compte.photo.reminder': 'N\'oubliez pas de cliquer sur "Mettre à jour" pour enregistrer votre nouvelle photo.',
            'compte.subscription.current': 'Mon abonnement',
            'compte.subscription.expire': 'Date d\'expiration',
            'compte.subscription.viewOffers': 'Voir mes offres',
            'compte.subscription.detail': 'Détail de l\'abonnement',
            'compte.subscription.planName': 'Nom du plan',
            'compte.subscription.subtitle': 'Sous-titre',
            'compte.subscription.paymentStatus': 'Statut de paiement',
            'compte.subscription.paid': 'Payé',
            'compte.subscription.period': 'Période',
            'compte.subscription.amountPaid': 'Montant payé',
            'compte.subscription.paymentMethod': 'Moyen de paiement',
            'compte.subscription.benefits': 'Avantages inclus',
            'compte.subscription.monthly': 'Mensuel',
            'compte.subscription.yearly': 'Annuel',
            'compte.subscription.subscribe': 'S\'abonner',
            'compte.subscription.upgrade': 'Passer au Premium',
            'compte.invoices.search': 'Rechercher ici',
            'compte.invoices.allStatus': 'Tous les statuts',
            'compte.invoices.expired': 'Expiré',
            'compte.invoices.table.description': 'Description',
            'compte.invoices.table.period': 'Période',
            'compte.invoices.table.amountHT': 'Montant HT',
            'compte.save.loading': 'Enregistrement...',

            // Dashboard
            'dashboard.loading.title': 'Chargement du tableau de bord',
            'dashboard.loading.subtitle': 'Analyse des données en cours, veuillez patienter…',
            'dashboard.error.title': 'Impossible de charger les données',
            'dashboard.retry': 'Réessayer',
            'dashboard.searchProject': 'Rechercher par projet',
            'dashboard.overview.sites': 'Vue d\'ensemble des chantiers',
            'dashboard.overview.studies': 'Vue d\'ensemble des études',
            'dashboard.studies.distribution': 'Répartition des études (%)',
            'dashboard.studies.completed': 'Complétées',
            'dashboard.studies.initiated': 'Initiées',
            'dashboard.studies.notInitiated': 'Non initiées',
            'dashboard.indicators.progress': 'Taux moyen d\'avancement',
            'dashboard.indicators.budget': 'Budget global',
            'dashboard.budget.consumed': 'Consommé',
            'dashboard.budget.remaining': 'Restant',
            'dashboard.alerts.stock': 'Alertes stock matériaux',
            'dashboard.alerts.none': 'Aucune alerte',
            'dashboard.charts.progress': 'État d\'avancement',
            'dashboard.charts.incidents': 'Incidents signalés (7 jours)',
            'dashboard.tasks.critical': 'Tâches critiques à échéance',
            'dashboard.photos.recent': 'Photos récentes',
            'dashboard.performance.summary': 'Résumé des performances',
            'dashboard.performance.avgPresence': 'Présence moyenne',
            'dashboard.performance.lateTasks': 'Tâches en retard',
            'dashboard.performance.alertMaterials': 'Matériaux en alerte',
            'dashboard.rate.avg': 'Taux moyen',
            'dashboard.metrics.inProgress': 'En cours',
            'dashboard.metrics.delayed': 'En retard',
            'dashboard.metrics.pending': 'En attente',
            'dashboard.metrics.completed': 'Terminées',
            'dashboard.metrics.total': 'En ensemble',
            'dashboard.metrics.delivered': 'Livrées',
            'dashboard.metrics.budgetConsumed': 'Budget consommé',
            'dashboard.metrics.incidents7d': 'Incidents (7j)',

            // Common / Other
            'common.month.yearly': 'mois (annuel)',
            'common.month': 'mois',
            'common.year': 'an',
            'common.updateSave': 'Mettre à jour',
            'common.processing': 'Traitement...',
            'common.economize': 'Économisez',
            'common.unlimitedProjects': 'Projets illimités',
            'common.maxProjects': 'projet(s) maximum',
            'common.prioritySupport': 'Support prioritaire',
            'common.installments': 'Paiement en {{count}} fois',
            'common.yearlyDiscount': 'réduction en paiement annuel',
            'common.popular': 'POPULAIRE',
            'common.changePhoto': 'Changer la photo',

            // Generic Section Headers
            'requests.title': 'Demandes',
            'orders.title': 'Commandes',
            'subscriptions.title': 'Abonnements',
            'reclamations.title': 'Réclamations',

            // Users Page
            'users.subtitle': 'Créer, modifier, visualiser, rechercher, filtrer les utilisateurs inscrits',
            'users.table.user': 'Utilisateur',
            'users.table.registerDate': 'Date d\'inscription',
            'users.create': 'Nouvel Utilisateur',
            'users.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?',

            // Export
            'export.select': 'Format d\'exportation',
            'export.excel': 'Exporter en Excel',
            'export.pdf': 'Exporter en PDF',
            'export.success': 'Exportation réussie',
            'export.error': 'Erreur lors de l\'exportation',
        },
        EN: {
            'sidebar.dashboard': 'Dashboard',
            'sidebar.dashboardAdmin': 'Admin Dashboard',
            'sidebar.dashboardStudy': 'Study Dashboard',
            'sidebar.users': 'Users',
            'sidebar.subscriptions': 'Subscription Plans',
            'sidebar.subcontractors': 'Subcontractors',
            'sidebar.suppliers': 'Suppliers',
            'sidebar.settings': 'Settings',
            'sidebar.unitMeasure': 'Unit of Measure',
            'sidebar.documents': 'Documents',
            'sidebar.propertyType': 'Property Type',
            'sidebar.materialCategories': 'Material Categories',
            'sidebar.projects': 'Projects',
            'sidebar.requests': 'Requests',
            'sidebar.orders': 'Orders',
            'sidebar.myAccount': 'My Account',
            'sidebar.logout': 'Sign out',
            'sidebar.reclamations': 'Claims',
            'breadcrumb.helpSupport': 'Help & Support',
            'breadcrumb.language': 'Language',
            'breadcrumb.home': 'Home',
            'breadcrumb.dashboard': 'Dashboard',
            'profile.siteManager': 'Manager',
            'profile.subcontractor': 'Subcontractor',
            'profile.supplier': 'Supplier',
            'profile.admin': 'Administrator',
            'profile.bet': 'Technical Office',
            'profile.user': 'User',
            'profile.promoter': 'Promoter',
            'profile.moa': 'Project Owner',
            'profile.notaire': 'Notary',
            'profile.reservataire': 'Buyer',
            'profile.bank': 'Bank',
            'profile.agency': 'Agency',
            'profile.proprietaire': 'Owner',
            'profile.syndic': 'Property Manager',
            'profile.locataire': 'Tenant',
            'profile.prestataire': 'Service Provider',
            'profile.tom': 'TOM',
            'profile.worker': 'Worker',
            'common.search': 'Search',
            'common.searchPlaceholder': 'Search...',
            'common.filter': 'Filters',
            'common.export': 'Export',
            'common.add': 'Add',
            'common.edit': 'Edit',
            'common.delete': 'Delete',
            'common.save': 'Save',
            'common.cancel': 'Cancel',
            'common.close': 'Close',
            'common.next': 'Next',
            'common.previous': 'Previous',
            'common.loading': 'Loading...',
            'common.noData': 'No data',
            'common.actions': 'Actions',
            'common.status': 'Status',
            'common.date': 'Date',
            'common.view': 'View',
            'common.copy': 'Copy',
            'common.confirm': 'Confirm',
            'common.yes': 'Yes',
            'common.no': 'No',
            'common.active': 'Active',
            'common.inactive': 'Inactive',
            'common.all': 'All',
            'common.create': 'Create',
            'common.update': 'Update',
            'common.download': 'Download',
            'common.upload': 'Upload',
            'common.back': 'Back',
            'common.details': 'Details',
            'common.total': 'Total',
            'common.showing': 'Showing',
            'common.to': 'to',
            'common.of': 'of',
            'common.results': 'results',
            'notifications.title': 'Notifications',
            'notifications.newUser': 'New user registered',
            'notifications.newUserMessage': '{{name}} just registered',
            'notifications.noNotifications': 'No notifications',
            'notifications.markAllRead': 'Mark all as read',
            'dashboard.title': 'Dashboard',
            'dashboard.overview': 'Construction Sites Overview',
            'status.inProgress': 'In Progress',
            'status.delayed': 'Delayed',
            'status.pending': 'Pending',
            'status.completed': 'Completed',
            'users.title': 'User Management',
            'help.title': 'Help & Support',
            'help.description': 'Contact us for any questions or assistance. We are here to help!',
            'help.email': 'Email',
            'help.phone': 'Phone',
            'help.hours': 'Support hours:',
            'help.hoursValue': 'Monday - Friday, 08:00 AM - 06:00 PM',

            // Compte
            'compte.title': 'My Account',
            'compte.tabs.info': 'Personal Information',
            'compte.tabs.subscriptions': 'Subscriptions',
            'compte.tabs.invoices': 'Invoices',
            'compte.form.firstName': 'First Name',
            'compte.form.lastName': 'Last Name',
            'compte.form.phone': 'Phone Number',
            'compte.form.email': 'Email',
            'compte.form.address': 'Address',
            'compte.form.company': 'Company Name',
            'compte.form.profile': 'Profile',
            'compte.profile.cantEdit': 'Profile cannot be modified',
            'compte.photo.new': 'New Photo',
            'compte.photo.reminder': 'Don\'t forget to click "Update" to save your new photo.',
            'compte.subscription.current': 'My Subscription',
            'compte.subscription.expire': 'Expiration Date',
            'compte.subscription.viewOffers': 'View My Offers',
            'compte.subscription.detail': 'Subscription Detail',
            'compte.subscription.planName': 'Plan Name',
            'compte.subscription.subtitle': 'Subtitle',
            'compte.subscription.paymentStatus': 'Payment Status',
            'compte.subscription.paid': 'Paid',
            'compte.subscription.period': 'Period',
            'compte.subscription.amountPaid': 'Amount Paid',
            'compte.subscription.paymentMethod': 'Payment Method',
            'compte.subscription.benefits': 'Included Benefits',
            'compte.subscription.monthly': 'Monthly',
            'compte.subscription.yearly': 'Yearly',
            'compte.subscription.subscribe': 'Subscribe',
            'compte.subscription.upgrade': 'Upgrade to Premium',
            'compte.invoices.search': 'Search here',
            'compte.invoices.allStatus': 'All Statuses',
            'compte.invoices.expired': 'Expired',
            'compte.invoices.table.description': 'Description',
            'compte.invoices.table.period': 'Period',
            'compte.invoices.table.amountHT': 'Amount (Excl. Tax)',
            'compte.save.loading': 'Saving...',

            // Dashboard
            'dashboard.loading.title': 'Loading Dashboard',
            'dashboard.loading.subtitle': 'Analyzing data, please wait...',
            'dashboard.error.title': 'Unable to load data',
            'dashboard.retry': 'Retry',
            'dashboard.searchProject': 'Search by project',
            'dashboard.overview.sites': 'Construction Sites Overview',
            'dashboard.overview.studies': 'Studies Overview',
            'dashboard.studies.distribution': 'Studies Distribution (%)',
            'dashboard.studies.completed': 'Completed',
            'dashboard.studies.initiated': 'Initiated',
            'dashboard.studies.notInitiated': 'Not Initiated',
            'dashboard.indicators.progress': 'Average Progress Rate',
            'dashboard.indicators.budget': 'Global Budget',
            'dashboard.budget.consumed': 'Consumed',
            'dashboard.budget.remaining': 'Remaining',
            'dashboard.alerts.stock': 'Stock Alerts',
            'dashboard.alerts.none': 'No alerts',
            'dashboard.charts.progress': 'Progress Status',
            'dashboard.charts.incidents': 'Reported Incidents (7 days)',
            'dashboard.tasks.critical': 'Critical Tasks Due',
            'dashboard.photos.recent': 'Recent Photos',
            'dashboard.performance.summary': 'Performance Summary',
            'dashboard.performance.avgPresence': 'Average Presence',
            'dashboard.performance.lateTasks': 'Late Tasks',
            'dashboard.performance.alertMaterials': 'Materials in Alert',
            'dashboard.rate.avg': 'Average Rate',
            'dashboard.metrics.inProgress': 'In Progress',
            'dashboard.metrics.delayed': 'Delayed',
            'dashboard.metrics.pending': 'Pending',
            'dashboard.metrics.completed': 'Completed',
            'dashboard.metrics.total': 'Total',
            'dashboard.metrics.delivered': 'Delivered',
            'dashboard.metrics.budgetConsumed': 'Budget Consumed',
            'dashboard.metrics.incidents7d': 'Incidents (7d)',

            // Common / Other
            'common.month.yearly': 'month (yearly)',
            'common.month': 'month',
            'common.year': 'year',
            'common.updateSave': 'Update',
            'common.processing': 'Processing...',
            'common.economize': 'Save',
            'common.unlimitedProjects': 'Unlimited Projects',
            'common.maxProjects': 'project(s) maximum',
            'common.prioritySupport': 'Priority Support',
            'common.installments': 'Payment in {{count}} installments',
            'common.yearlyDiscount': 'discount on yearly payment',
            'common.popular': 'POPULAR',
            'common.changePhoto': 'Change Photo',

            // Generic Section Headers
            'requests.title': 'Requests',
            'orders.title': 'Orders',
            'subscriptions.title': 'Subscriptions',
            'reclamations.title': 'Claims',

            // Users Page
            'users.subtitle': 'Create, edit, view, search, filter registered users',
            'users.table.user': 'User',
            'users.table.registerDate': 'Registration Date',
            'users.create': 'New User',
            'users.deleteConfirm': 'Are you sure you want to delete this user?',

            // Export
            'export.select': 'Export Format',
            'export.excel': 'Export to Excel',
            'export.pdf': 'Export to PDF',
            'export.success': 'Export success',
            'export.error': 'Export error',
        }
    };

    constructor() {
        const savedLang = localStorage.getItem('language') as Language;
        if (savedLang && (savedLang === 'FR' || savedLang === 'EN')) {
            this.currentLang.set(savedLang);
        }
    }

    changeLanguage(lang: Language) {
        this.currentLang.set(lang);
        localStorage.setItem('language', lang);
    }

    translate(key: string, params?: { [key: string]: string | number }): string {
        const lang = this.currentLang();
        let text = this.translations[lang][key] || key;

        if (params) {
            Object.keys(params).forEach(param => {
                text = text.replace(`{{${param}}}`, String(params[param]));
            });
        }

        return text;
    }
}
