import { Injectable, signal } from '@angular/core';

export type Language = 'FR' | 'EN';

type Translations = {
    [key: string]: string;
};

@Injectable({
    providedIn: 'root'
})
export class LanguageService {
    currentLang = signal<Language>('FR');

    private translations: { FR: Translations; EN: Translations } = {
        FR: {
            'sidebar.dashboard': 'Dashboard',
            'sidebar.dashboardAdmin': 'Tableau de bord Admin',
            'sidebar.dashboardStudy': 'Tableau de bord Études',
            'sidebar.users': 'Utilisateurs',
            'sidebar.subscriptions': 'Plans d\'abonnement',
            'sidebar.subcontractors': 'Sous-traitants',
            'sidebar.suppliers': 'Fournisseurs',
            'sidebar.settings': 'Paramètres',
            'sidebar.unitMeasure': 'Unités de mesure',
            'sidebar.documents': 'Documents',
            'sidebar.propertyType': 'Types de propriété',
            'sidebar.materialCategories': 'Catégories de matériaux',
            'sidebar.projects': 'Projets',
            'sidebar.requests': 'Demandes',
            'sidebar.orders': 'Commandes',
            'sidebar.myAccount': 'Mon compte',
            'sidebar.logout': 'Déconnexion',
            'sidebar.reclamations': 'Réclamations',
            'breadcrumb.helpSupport': 'Aide & Support',
            'breadcrumb.language': 'Langue',
            'breadcrumb.home': 'Accueil',
            'breadcrumb.dashboard': 'Tableau de bord',
            'profile.siteManager': 'Manager',
            'profile.subcontractor': 'Sous-traitant',
            'profile.supplier': 'Fournisseur',
            'profile.admin': 'Administrateur',
            'profile.bet': 'Bureau d\'études',
            'profile.user': 'Utilisateur',
            'profile.promoter': 'Promoteur',
            'profile.moa': 'Maître d\'ouvrage',
            'profile.notaire': 'Notaire',
            'profile.reservataire': 'Réservataire',
            'profile.bank': 'Banque',
            'profile.agency': 'Agence',
            'profile.proprietaire': 'Propriétaire',
            'profile.syndic': 'Syndic',
            'profile.locataire': 'Locataire',
            'profile.prestataire': 'Prestataire',
            'profile.tom': 'TOM',
            'profile.worker': 'Ouvrier',
            'common.search': 'Rechercher',
            'common.searchPlaceholder': 'Rechercher...',
            'common.filter': 'Filtres',
            'common.export': 'Exporter',
            'common.add': 'Ajouter',
            'common.edit': 'Modifier',
            'common.delete': 'Supprimer',
            'common.save': 'Enregistrer', // Unique key
            'common.cancel': 'Annuler',
            'common.close': 'Fermer',
            'common.next': 'Suivant',
            'common.previous': 'Précédent',
            'common.loading': 'Chargement...',
            'common.noData': 'Aucune donnée disponible',
            'common.actions': 'Actions',
            'common.status': 'Statut',
            'common.date': 'Date',
            'common.view': 'Voir',
            'common.copy': 'Copier',
            'common.confirm': 'Confirmer',
            'common.yes': 'Oui',
            'common.no': 'Non',
            'common.active': 'Actif',
            'common.inactive': 'Inactif',
            'common.all': 'Tous',
            'common.create': 'Créer',
            'common.update': 'Mettre à jour',
            'common.download': 'Télécharger',
            'common.upload': 'Téléverser',
            'common.back': 'Retour',
            'common.details': 'Détails',
            'common.total': 'Total',
            'common.showing': 'Affichage de',
            'common.to': 'à',
            'common.of': 'sur',
            'common.results': 'résultats',
            'notifications.title': 'Notifications',
            'notifications.newUser': 'Nouvel utilisateur inscrit',
            'notifications.newUserMessage': '{{name}} vient de s\'inscrire',
            'notifications.noNotifications': 'Aucune notification',
            'notifications.markAllRead': 'Tout marquer comme lu',
            'dashboard.title': 'Tableau de bord',
            'dashboard.overview': 'Vue d\'ensemble des chantiers',
            'status.inProgress': 'En cours',
            'status.delayed': 'En retard',
            'status.pending': 'En attente',
            'status.completed': 'Terminé',
            'users.title': 'Gestion des utilisateurs',
            'help.title': 'Aide & Support',
            'help.description': 'Contactez-nous pour toute question ou assistance. Nous sommes là pour vous aider !',
            'help.email': 'Email',
            'help.phone': 'Téléphone',
            'help.hours': 'Heures de support :',
            'help.hoursValue': 'Lundi - Vendredi, 08h00 - 18h00',

            // Compte
            'compte.title': 'Mon compte',
            'compte.tabs.info': 'Informations personnelles',
            'compte.tabs.subscriptions': 'Abonnements',
            'compte.tabs.invoices': 'Factures',
            'compte.form.firstName': 'Prénom',
            'compte.form.lastName': 'Nom',
            'compte.form.phone': 'Numéro de téléphone',
            'compte.form.email': 'Email',
            'compte.form.address': 'Adresse',
            'compte.form.company': 'Nom de l\'entreprise',
            'compte.form.profile': 'Profil',
            'compte.profile.cantEdit': 'Le profil ne peut pas être modifié',
            'compte.photo.new': 'Nouvelle photo',
            'compte.photo.reminder': 'N\'oubliez pas de cliquer sur "Mettre à jour" pour enregistrer votre nouvelle photo.',
            'compte.subscription.current': 'Mon abonnement',
            'compte.subscription.expire': 'Date d\'expiration',
            'compte.subscription.viewOffers': 'Voir mes offres',
            'compte.subscription.detail': 'Détail de l\'abonnement',
            'compte.subscription.planName': 'Nom du plan',
            'compte.subscription.subtitle': 'Sous-titre',
            'compte.subscription.paymentStatus': 'Statut de paiement',
            'compte.subscription.paid': 'Payé',
            'compte.subscription.period': 'Période',
            'compte.subscription.amountPaid': 'Montant payé',
            'compte.subscription.paymentMethod': 'Moyen de paiement',
            'compte.subscription.benefits': 'Avantages inclus',
            'compte.subscription.monthly': 'Mensuel',
            'compte.subscription.yearly': 'Annuel',
            'compte.subscription.subscribe': 'S\'abonner',
            'compte.subscription.upgrade': 'Passer au Premium',
            'compte.invoices.search': 'Rechercher ici',
            'compte.invoices.allStatus': 'Tous les statuts',
            'compte.invoices.expired': 'Expiré',
            'compte.invoices.table.description': 'Description',
            'compte.invoices.table.period': 'Période',
            'compte.invoices.table.amountHT': 'Montant HT',
            'compte.save.loading': 'Enregistrement...',

            // Dashboard
            'dashboard.loading.title': 'Chargement du tableau de bord',
            'dashboard.loading.subtitle': 'Analyse des données en cours, veuillez patienter…',
            'dashboard.error.title': 'Impossible de charger les données',
            'dashboard.retry': 'Réessayer',
            'dashboard.searchProject': 'Rechercher par projet',
            'dashboard.overview.sites': 'Vue d\'ensemble des chantiers',
            'dashboard.overview.studies': 'Vue d\'ensemble des études',
            'dashboard.studies.distribution': 'Répartition des études (%)',
            'dashboard.studies.completed': 'Complétées',
            'dashboard.studies.initiated': 'Initiées',
            'dashboard.studies.notInitiated': 'Non initiées',
            'dashboard.indicators.progress': 'Taux moyen d\'avancement',
            'dashboard.indicators.budget': 'Budget global',
            'dashboard.budget.consumed': 'Consommé',
            'dashboard.budget.remaining': 'Restant',
            'dashboard.alerts.stock': 'Alertes stock matériaux',
            'dashboard.alerts.none': 'Aucune alerte',
            'dashboard.charts.progress': 'État d\'avancement',
            'dashboard.charts.incidents': 'Incidents signalés (7 jours)',
            'dashboard.tasks.critical': 'Tâches critiques à échéance',
            'dashboard.photos.recent': 'Photos récentes',
            'dashboard.performance.summary': 'Résumé des performances',
            'dashboard.performance.avgPresence': 'Présence moyenne',
            'dashboard.performance.lateTasks': 'Tâches en retard',
            'dashboard.performance.alertMaterials': 'Matériaux en alerte',
            'dashboard.rate.avg': 'Taux moyen',
            'dashboard.metrics.inProgress': 'En cours',
            'dashboard.metrics.delayed': 'En retard',
            'dashboard.metrics.pending': 'En attente',
            'dashboard.metrics.completed': 'Terminées',
            'dashboard.metrics.total': 'En ensemble',
            'dashboard.metrics.delivered': 'Livrées',
            'dashboard.metrics.budgetConsumed': 'Budget consommé',
            'dashboard.metrics.incidents7d': 'Incidents (7j)',

            // Common / Other
            'common.month.yearly': 'mois (annuel)',
            'common.month': 'mois',
            'common.year': 'an',
            'common.updateSave': 'Mettre à jour',
            'common.processing': 'Traitement...',
            'common.economize': 'Économisez',
            'common.unlimitedProjects': 'Projets illimités',
            'common.maxProjects': 'projet(s) maximum',
            'common.prioritySupport': 'Support prioritaire',
            'common.installments': 'Paiement en {{count}} fois',
            'common.yearlyDiscount': 'réduction en paiement annuel',
            'common.popular': 'POPULAIRE',
            'common.changePhoto': 'Changer la photo',

            // Generic Section Headers
            'requests.title': 'Demandes',
            'orders.title': 'Commandes',
            'subscriptions.title': 'Abonnements',
            'reclamations.title': 'Réclamations',

            // Users Page
            'users.subtitle': 'Créer, modifier, visualiser, rechercher, filtrer les utilisateurs inscrits',
            'users.table.user': 'Utilisateur',
            'users.table.registerDate': 'Date d\'inscription',
            'users.create': 'Nouvel Utilisateur',
            'users.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?',

            // Export
            'export.select': 'Format d\'exportation',
            'export.excel': 'Exporter',
            'export.pdf': 'Exporter en PDF',
            'export.success': 'Exportation réussie',
            'export.error': 'Erreur lors de l\'exportation',

            // Projects
            'projects.title': 'Projets en cours',
            'projects.description': 'Consultez la liste de vos chantiers actuellement en cours et suivez leur avancement en temps réel.',
            'projects.newProject': 'Nouveau Projet',
            'projects.searchByProject': 'Rechercher par projet',
            'projects.allPeriods': 'Toutes les périodes',
            'projects.thisYear': 'Cette année',
            'projects.lastYear': 'Année dernière',
            'projects.older': 'Plus ancien',
            'projects.allStatuses': 'Tous les statuts',
            'projects.active': 'Actif',
            'projects.inactive': 'Inactif',
            'projects.completed': 'Terminé',
            'projects.inProgress': 'En cours',
            'projects.progress': 'Progression',
            'projects.loadingProjects': 'Chargement des projets...',
            'projects.noProjectFound': 'Aucun projet trouvé',
            'projects.retry': 'Réessayer',
            'projects.perPage': 'Projets par page :',
            'projects.page': 'Page',
            'projects.on': 'sur',
            'projects.noImage': 'Aucune image',
            'projects.blocked': 'BLOQUÉ',
            'projects.blockedTitle': 'Projet Bloqué',
            'projects.blockedRestricted': 'Accès restreint',
            'projects.blockedMessage': 'Ce projet est bloqué jusqu\'au renouvellement de votre abonnement. Veuillez mettre à jour votre plan pour y accéder.',
            'projects.subscriptions': 'Abonnements',
            'projects.showing': 'Affichage de',
            'projects.export': 'Exporter',

            // Project Detail Tabs
            'projectDetail.presentation': 'Présentation',
            'projectDetail.tasks': 'Tâches',
            'projectDetail.team': 'Équipe',
            'projectDetail.lots': 'Lots',
            'projectDetail.documents': 'Documents',
            'projectDetail.stock': 'Stock',
            'projectDetail.alert': 'Signalement',
            'projectDetail.studyBet': 'Etude Bet',
            'projectDetail.pointingAddress': 'Adresse Pointage',
            'projectDetail.viewQrCode': 'Voir QR Code',
            'projectDetail.qrCode': 'QR code',
            'projectDetail.scanMessage': 'Scannez avec votre téléphone pour ouvrir les détails du projet.',
            'projectDetail.project': 'Projet',
            'projectDetail.status': 'Statut',
            'projectDetail.updateDate': 'Date MAJ',
            'projectDetail.address': 'Adresse',
            'projectDetail.print': 'Imprimer',
            'projectDetail.download': 'Télécharger',
            'projectDetail.qrUnavailable': 'QR code indisponible',
            'projectDetail.loading': 'Chargement...',
            'projectDetail.selectTab': 'Sélectionnez un onglet',

            // Project Detail - Statuses
            'projectStatus.active': 'Actif',
            'projectStatus.inactive': 'Inactif',
            'projectStatus.completed': 'Terminé',
            'projectStatus.inProgress': 'En cours',
            'projectStatus.pending': 'En attente',
            'projectStatus.blocked': 'Bloqué',

            // Project Detail - Empty Messages
            'projectDetail.noData': 'Aucune donnée disponible',
            'projectDetail.noTasks': 'Aucune tâche',
            'projectDetail.noTeam': 'Aucun membre d\'équipe',
            'projectDetail.noDocuments': 'Aucun document',
            'projectDetail.noStock': 'Aucun stock',
            'projectDetail.noAlerts': 'Aucune alerte',

            // Project Detail - Confirmations
            'projectDetail.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer ?',
            'projectDetail.saveSuccess': 'Enregistré avec succès',
            'projectDetail.saveError': 'Erreur lors de l\'enregistrement',

            // Project Detail - Buttons
            'projectDetail.addTask': 'Ajouter une tâche',
            'projectDetail.addMember': 'Ajouter un membre',
            'projectDetail.uploadDocument': 'Téléverser un document',
            'projectDetail.addStock': 'Ajouter au stock',
            'projectDetail.reportIssue': 'Signaler un problème',

            // Dashboard Admin
            'dashboardAdmin.title': 'Tableau de bord Administrateur',
            'dashboardAdmin.users.total': 'Total utilisateurs',
            'dashboardAdmin.users.active': 'Utilisateurs actifs',
            'dashboardAdmin.users.pending': 'En attente de validation',
            'dashboardAdmin.projects.total': 'Total projets',
            'dashboardAdmin.subscriptions.total': 'Total Abonnements',
            'dashboardAdmin.subscriptions.active': 'Abonnements Actifs',
            'dashboardAdmin.subscriptions.expired': 'Abonnements Expirés',
            'dashboardAdmin.revenue.total': 'Revenus Cumulés',
            'dashboardAdmin.revenue.monthly': 'Revenus Mensuels',
            'dashboardAdmin.stats': 'Statistiques',
            'dashboardAdmin.overview': 'Vue d\'ensemble',
            'dashboardAdmin.charts.subscriptions': 'Évolution des Abonnements',
            'dashboardAdmin.charts.revenue': 'Revenus Mensuels',
            'dashboardAdmin.charts.profiles': 'Répartition des profils',
            'dashboardAdmin.charts.plans': 'Distribution des Plans',
            'dashboardAdmin.invoices.title': 'Dernières Factures Payées',
            'dashboardAdmin.invoices.invoice': 'Facture',
            'dashboardAdmin.invoices.user': 'Utilisateur',
            'dashboardAdmin.invoices.plan': 'Plan',
            'dashboardAdmin.invoices.amount': 'Montant',
            'dashboardAdmin.invoices.date': 'Date',
            'dashboardAdmin.invoices.status': 'Statut',
            'dashboardAdmin.invoices.paid': 'Payé',
            'dashboardAdmin.invoices.unpaid': 'Impayé',
            'dashboardAdmin.invoices.noData': 'Aucune facture disponible',
            'dashboardAdmin.pagination.showing': 'Affichage de',
            'dashboardAdmin.pagination.to': 'à',
            'dashboardAdmin.pagination.of': 'sur',
            'dashboardAdmin.pagination.results': 'résultats',
            'dashboardAdmin.pagination.previous': 'Précédent',
            'dashboardAdmin.pagination.next': 'Suivant',

            // Project Presentation
            'projectPresentation.progression': 'Progression',
            'projectPresentation.loadingProgress': 'Chargement de la progression...',
            'projectPresentation.surface': 'Surface',
            'projectPresentation.lots': 'Lots',
            'projectPresentation.startDate': 'Début',
            'projectPresentation.endDate': 'Fin prévue',
            'projectPresentation.budget': 'Budget',
            'projectPresentation.used': 'Utilisé',
            'projectPresentation.status': 'Statut',
            'projectPresentation.updating': 'Mise à jour...',
            'projectPresentation.inProgress': 'En cours',
            'projectPresentation.paused': 'En pause',
            'projectPresentation.completed': 'Terminé',
            'projectPresentation.currentStatus': 'Statut actuel',
            'projectPresentation.generalInfo': 'Informations générales',
            'projectPresentation.progressState': 'État d\'avancement',
            'projectPresentation.budgetTab': 'Budget',
            'projectPresentation.add': 'Ajouter',
            'projectPresentation.description': 'Description',
            'projectPresentation.amount': 'Montant',
            'projectPresentation.location': 'Emplacement',
            'projectPresentation.numberOfLots': 'Nombre de lots',
            'projectPresentation.dueDate': 'Date d\'échéance',
            'projectPresentation.numberOfRooms': 'Nombre de pièces',
            'projectPresentation.commonEquipment': 'Équipements communs',
            'projectPresentation.budgetInfo': 'Informations budgétaires',

            // ============ TEAM COMPONENT ============
            'team.searchPlaceholder': 'Rechercher ici...',
            'team.filterByRole': 'Filtrer par rôle',
            'team.allRoles': 'Tous les rôles',
            'team.newMember': 'Nouveau membre',
            'team.name': 'Nom',
            'team.role': 'Rôle',
            'team.phone': 'Téléphone',
            'team.present': 'Présent',
            'team.action': 'Action',
            'team.loading': 'Chargement en cours...',
            'team.retry': 'Réessayer',
            'team.yes': 'Oui',
            'team.no': 'Non',
            'team.noMembers': 'Aucun membre d\'équipe trouvé',
            'team.startAddingMembers': 'Commencez par ajouter des membres à votre équipe',
            'team.previous': 'Précédent',
            'team.next': 'Suivant',
            'team.addNewMember': 'Ajouter un nouveau membre',
            'team.lastName': 'Nom',
            'team.firstName': 'Prénom',
            'team.email': 'Email',
            'team.birthDate': 'Date de naissance',
            'team.birthPlace': 'Lieu de naissance',
            'team.address': 'Adresse',
            'team.profilePhoto': 'Photo de profil',
            'team.password': 'Mot de passe',
            'team.cancel': 'Annuler',
            'team.add': 'Ajouter',
            'team.adding': 'Ajout...',
            'team.details': 'Détails',
            'team.daysPresent': 'Jours présents',
            'team.hoursWorked': 'Heures travaillées',
            'team.tasksCompleted': 'Tâches terminées',
            'team.performance': 'Performance',
            'team.taskDistribution': 'Répartition des tâches (%)',
            'team.toDo': 'À Faire',
            'team.inProgress': 'En cours',
            'team.completed': 'Terminés',
            'team.late': 'En retard',
            'team.presenceHistory': 'Historique des présences',
            'team.filterByDate': 'Filtrer par date',
            'team.entry': 'Entrée',
            'team.exit': 'Sortie',
            'team.total': 'Total',
            'team.noPresenceHistory': 'Aucun historique de présence disponible',
            'team.totalHoursWorked': 'Total Heures travaillées',
            'team.close': 'Fermer',
            'team.worker': 'Ouvrier',
            'team.acceptedFormats': 'Formats acceptés : JPG, PNG, GIF (Max 5MB)',
            'team.passwordMinLength': 'Mot de passe (minimum 6 caractères)',

            // ============ DOCUMENTS COMPONENT ============
            'documents.title': 'Documents',
            'documents.search': 'Rechercher un document...',
            'documents.addDocument': 'Ajouter un document',
            'documents.name': 'Nom',
            'documents.type': 'Type',
            'documents.size': 'Taille',
            'documents.date': 'Date',
            'documents.actions': 'Actions',
            'documents.download': 'Télécharger',
            'documents.delete': 'Supprimer',
            'documents.view': 'Voir',
            'documents.noDocuments': 'Aucun document trouvé',
            'documents.uploadDocument': 'Téléverser un document',
            'documents.dragDrop': 'Glissez et déposez vos fichiers ici',
            'documents.or': 'ou',
            'documents.browse': 'Parcourir',
            'documents.cancel': 'Annuler',
            'documents.upload': 'Téléverser',
            'documents.uploading': 'Téléversement...',
            'documents.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer ce document ?',
            'documents.confirmDelete': 'Confirmer la suppression',
            'documents.category': 'Catégorie',
            'documents.allCategories': 'Toutes les catégories',
            'documents.administrative': 'Administratif',
            'documents.technical': 'Technique',
            'documents.financial': 'Financier',
            'documents.other': 'Autre',

            // ============ STOCK COMPONENT ============
            'stock.title': 'Stock',
            'stock.search': 'Rechercher un article...',
            'stock.addArticle': 'Ajouter un article',
            'stock.articleName': 'Nom de l\'article',
            'stock.category': 'Catégorie',
            'stock.quantity': 'Quantité',
            'stock.unit': 'Unité',
            'stock.minStock': 'Stock minimum',
            'stock.currentStock': 'Stock actuel',
            'stock.status': 'Statut',
            'stock.actions': 'Actions',
            'stock.inStock': 'En stock',
            'stock.lowStock': 'Stock bas',
            'stock.outOfStock': 'Rupture de stock',
            'stock.edit': 'Modifier',
            'stock.delete': 'Supprimer',
            'stock.noArticles': 'Aucun article en stock',
            'stock.addNewArticle': 'Ajouter un nouvel article',
            'stock.editArticle': 'Modifier l\'article',
            'stock.cancel': 'Annuler',
            'stock.save': 'Enregistrer',
            'stock.saving': 'Enregistrement...',
            'stock.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cet article ?',
            'stock.confirmDelete': 'Confirmer la suppression',
            'stock.allCategories': 'Toutes les catégories',
            'stock.materials': 'Matériaux',
            'stock.tools': 'Outils',
            'stock.equipment': 'Équipements',
            'stock.consumables': 'Consommables',
            'stock.supplier': 'Fournisseur',
            'stock.unitPrice': 'Prix unitaire',
            'stock.totalValue': 'Valeur totale',
            'stock.lastUpdated': 'Dernière mise à jour',
            'stock.addStock': 'Ajouter du stock',
            'stock.removeStock': 'Retirer du stock',
            'stock.movement': 'Mouvement',
            'stock.movementHistory': 'Historique des mouvements',

            // ============ LOTS COMPONENT ============
            'lots.title': 'Lots',
            'lots.search': 'Rechercher un lot...',
            'lots.addLot': 'Ajouter un lot',
            'lots.lotNumber': 'Numéro de lot',
            'lots.lotName': 'Nom du lot',
            'lots.description': 'Description',
            'lots.subcontractor': 'Sous-traitant',
            'lots.budget': 'Budget',
            'lots.progress': 'Avancement',
            'lots.status': 'Statut',
            'lots.actions': 'Actions',
            'lots.notStarted': 'Non démarré',
            'lots.inProgress': 'En cours',
            'lots.completed': 'Terminé',
            'lots.suspended': 'Suspendu',
            'lots.noLots': 'Aucun lot trouvé',
            'lots.addNewLot': 'Ajouter un nouveau lot',
            'lots.editLot': 'Modifier le lot',
            'lots.cancel': 'Annuler',
            'lots.save': 'Enregistrer',
            'lots.saving': 'Enregistrement...',
            'lots.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer ce lot ?',
            'lots.confirmDelete': 'Confirmer la suppression',
            'lots.assignSubcontractor': 'Assigner un sous-traitant',
            'lots.selectSubcontractor': 'Sélectionner un sous-traitant',
            'lots.noSubcontractor': 'Aucun sous-traitant assigné',
            'lots.startDate': 'Date de début',
            'lots.endDate': 'Date de fin',
            'lots.estimatedBudget': 'Budget estimé',
            'lots.actualBudget': 'Budget réel',
            'lots.view': 'Voir',
            'lots.edit': 'Modifier',
            'lots.delete': 'Supprimer',

            // ============ ALERT/SIGNALEMENT COMPONENT ============
            'alert.title': 'Signalements',
            'alert.search': 'Rechercher un signalement...',
            'alert.addAlert': 'Nouveau signalement',
            'alert.alertType': 'Type de signalement',
            'alert.priority': 'Priorité',
            'alert.status': 'Statut',
            'alert.date': 'Date',
            'alert.reportedBy': 'Signalé par',
            'alert.description': 'Description',
            'alert.actions': 'Actions',
            'alert.high': 'Haute',
            'alert.medium': 'Moyenne',
            'alert.low': 'Basse',
            'alert.open': 'Ouvert',
            'alert.inProgress': 'En cours',
            'alert.resolved': 'Résolu',
            'alert.closed': 'Fermé',
            'alert.noAlerts': 'Aucun signalement',
            'alert.addNewAlert': 'Ajouter un signalement',
            'alert.editAlert': 'Modifier le signalement',
            'alert.cancel': 'Annuler',
            'alert.save': 'Enregistrer',
            'alert.saving': 'Enregistrement...',
            'alert.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer ce signalement ?',
            'alert.confirmDelete': 'Confirmer la suppression',
            'alert.safety': 'Sécurité',
            'alert.quality': 'Qualité',
            'alert.delay': 'Retard',
            'alert.material': 'Matériel',
            'alert.other': 'Autre',
            'alert.location': 'Localisation',
            'alert.photos': 'Photos',
            'alert.addPhotos': 'Ajouter des photos',
            'alert.view': 'Voir',
            'alert.edit': 'Modifier',
            'alert.delete': 'Supprimer',
            'alert.resolve': 'Résoudre',
            'alert.reopen': 'Rouvrir',
            'alert.allTypes': 'Tous les types',
            'alert.allPriorities': 'Toutes les priorités',
            'alert.allStatuses': 'Tous les statuts',

            // ============ STUDY BET COMPONENT ============
            'studyBet.title': 'Études BET',
            'studyBet.search': 'Rechercher une étude...',
            'studyBet.addStudy': 'Nouvelle étude',
            'studyBet.studyName': 'Nom de l\'étude',
            'studyBet.studyType': 'Type d\'étude',
            'studyBet.office': 'Bureau d\'études',
            'studyBet.status': 'Statut',
            'studyBet.deliveryDate': 'Date de livraison',
            'studyBet.actions': 'Actions',
            'studyBet.pending': 'En attente',
            'studyBet.inProgress': 'En cours',
            'studyBet.delivered': 'Livré',
            'studyBet.validated': 'Validé',
            'studyBet.rejected': 'Rejeté',
            'studyBet.noStudies': 'Aucune étude trouvée',
            'studyBet.addNewStudy': 'Ajouter une étude',
            'studyBet.editStudy': 'Modifier l\'étude',
            'studyBet.cancel': 'Annuler',
            'studyBet.save': 'Enregistrer',
            'studyBet.saving': 'Enregistrement...',
            'studyBet.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cette étude ?',
            'studyBet.confirmDelete': 'Confirmer la suppression',
            'studyBet.structural': 'Structure',
            'studyBet.electrical': 'Électricité',
            'studyBet.plumbing': 'Plomberie',
            'studyBet.hvac': 'CVC',
            'studyBet.architectural': 'Architecture',
            'studyBet.geotechnical': 'Géotechnique',
            'studyBet.other': 'Autre',
            'studyBet.documents': 'Documents',
            'studyBet.comments': 'Commentaires',
            'studyBet.version': 'Version',
            'studyBet.view': 'Voir',
            'studyBet.edit': 'Modifier',
            'studyBet.delete': 'Supprimer',
            'studyBet.validate': 'Valider',
            'studyBet.reject': 'Rejeter',
            'studyBet.download': 'Télécharger',

            // ============ POINTING ADDRESS COMPONENT ============
            'pointingAddress.title': 'Adresse de pointage',
            'pointingAddress.search': 'Rechercher...',
            'pointingAddress.addAddress': 'Ajouter une adresse',
            'pointingAddress.addressName': 'Nom de l\'adresse',
            'pointingAddress.fullAddress': 'Adresse complète',
            'pointingAddress.latitude': 'Latitude',
            'pointingAddress.longitude': 'Longitude',
            'pointingAddress.radius': 'Rayon (mètres)',
            'pointingAddress.status': 'Statut',
            'pointingAddress.actions': 'Actions',
            'pointingAddress.active': 'Actif',
            'pointingAddress.inactive': 'Inactif',
            'pointingAddress.noAddresses': 'Aucune adresse de pointage',
            'pointingAddress.addNewAddress': 'Ajouter une adresse de pointage',
            'pointingAddress.editAddress': 'Modifier l\'adresse',
            'pointingAddress.cancel': 'Annuler',
            'pointingAddress.save': 'Enregistrer',
            'pointingAddress.saving': 'Enregistrement...',
            'pointingAddress.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cette adresse ?',
            'pointingAddress.confirmDelete': 'Confirmer la suppression',
            'pointingAddress.selectOnMap': 'Sélectionner sur la carte',
            'pointingAddress.currentLocation': 'Position actuelle',
            'pointingAddress.view': 'Voir',
            'pointingAddress.edit': 'Modifier',
            'pointingAddress.delete': 'Supprimer',
            'pointingAddress.activate': 'Activer',
            'pointingAddress.deactivate': 'Désactiver',

            // ============ STATUS REPORT/ALBUMS COMPONENT ============
            'statusReport.albumsView': 'Vue Albums',
            'statusReport.graphView': 'Vue Graphique',
            'statusReport.indicatorsTable': 'Tableau indicateurs',
            'statusReport.viewPhotos': 'Voir les photos',
            'statusReport.editAlbum': 'Modifier l\'album',
            'statusReport.deleteAlbum': 'Supprimer l\'album',
            'statusReport.photos': 'photos',
            'statusReport.step': 'Étape',
            'statusReport.percentage': '%Pourcentage',
            'statusReport.updateDate': 'Date Mise À Jour',
            'statusReport.selectPercentage': 'Sélectionner une pourcentage',
            'statusReport.close': 'Fermer',
            'statusReport.createAlbum': 'Créer un nouvel album',
            'statusReport.albumName': 'Nom de l\'album',
            'statusReport.description': 'Description',
            'statusReport.albumPhotos': 'Photos de l\'album',
            'statusReport.clickToAdd': 'Cliquez pour ajouter des photos ou glissez-déposez',
            'statusReport.acceptedFormats': 'PNG, JPG, JPEG jusqu\'à 10MB',
            'statusReport.selectedPhotos': 'Photos sélectionnées',
            'statusReport.cancel': 'Annuler',
            'statusReport.create': 'Créer',
            'statusReport.modify': 'Modifier',
            'statusReport.currentPhotos': 'Photos actuelles',
            'statusReport.addNewPhotos': 'Ajouter de nouvelles photos',
            'statusReport.confirmDeletion': 'Confirmer la suppression',
            'statusReport.deleteConfirmMessage': 'Êtes-vous sûr de vouloir supprimer l\'album',
            'statusReport.irreversibleAction': 'Cette action est irréversible.',
            'statusReport.noCancel': 'Non, annuler',
            'statusReport.yesDelete': 'Oui, supprimer',
            'statusReport.noPhotos': 'Aucune photo dans cet album',

            // Logout Confirmation
            'logout.confirmTitle': 'Confirmer la déconnexion',
            'logout.confirmMessage': 'Êtes-vous sûr de vouloir vous déconnecter ?',
            'logout.confirm': 'Se déconnecter',
        },
        EN: {
            'sidebar.dashboard': 'Dashboard',
            'sidebar.dashboardAdmin': 'Admin Dashboard',
            'sidebar.dashboardStudy': 'Study Dashboard',
            'sidebar.users': 'Users',
            'sidebar.subscriptions': 'Subscription Plans',
            'sidebar.subcontractors': 'Subcontractors',
            'sidebar.suppliers': 'Suppliers',

            'sidebar.settings': 'Settings',
            'sidebar.unitMeasure': 'Unit of Measure',
            'sidebar.documents': 'Documents',
            'sidebar.propertyType': 'Property Type',
            'sidebar.materialCategories': 'Material Categories',
            'sidebar.projects': 'Projects',
            'sidebar.requests': 'Requests',
            'sidebar.orders': 'Orders',
            'sidebar.myAccount': 'My Account',
            'sidebar.logout': 'Sign out',
            'sidebar.reclamations': 'Claims',
            'breadcrumb.helpSupport': 'Help & Support',
            'breadcrumb.language': 'Language',
            'breadcrumb.home': 'Home',
            'breadcrumb.dashboard': 'Dashboard',
            'profile.siteManager': 'Manager',
            'profile.subcontractor': 'Subcontractor',
            'profile.supplier': 'Supplier',
            'profile.admin': 'Administrator',
            'profile.bet': 'Technical Office',
            'profile.user': 'User',
            'profile.promoter': 'Promoter',
            'profile.moa': 'Project Owner',
            'profile.notaire': 'Notary',
            'profile.reservataire': 'Buyer',
            'profile.bank': 'Bank',
            'profile.agency': 'Agency',
            'profile.proprietaire': 'Owner',
            'profile.syndic': 'Property Manager',
            'profile.locataire': 'Tenant',
            'profile.prestataire': 'Service Provider',
            'profile.tom': 'TOM',
            'profile.worker': 'Worker',
            'common.search': 'Search',
            'common.searchPlaceholder': 'Search...',
            'common.filter': 'Filters',
            'common.export': 'Export',
            'common.add': 'Add',
            'common.edit': 'Edit',
            'common.delete': 'Delete',
            'common.save': 'Save',
            'common.cancel': 'Cancel',
            'common.close': 'Close',
            'common.next': 'Next',
            'common.previous': 'Previous',
            'common.loading': 'Loading...',
            'common.noData': 'No data',
            'common.actions': 'Actions',
            'common.status': 'Status',
            'common.date': 'Date',
            'common.view': 'View',
            'common.copy': 'Copy',
            'common.confirm': 'Confirm',
            'common.yes': 'Yes',
            'common.no': 'No',
            'common.active': 'Active',
            'common.inactive': 'Inactive',
            'common.all': 'All',
            'common.create': 'Create',
            'common.update': 'Update',
            'common.download': 'Download',
            'common.upload': 'Upload',
            'common.back': 'Back',
            'common.details': 'Details',
            'common.total': 'Total',
            'common.showing': 'Showing',
            'common.to': 'to',
            'common.of': 'of',
            'common.results': 'results',
            'notifications.title': 'Notifications',
            'notifications.newUser': 'New user registered',
            'notifications.newUserMessage': '{{name}} just registered',
            'notifications.noNotifications': 'No notifications',
            'notifications.markAllRead': 'Mark all as read',
            'dashboard.title': 'Dashboard',
            'dashboard.overview': 'Construction Sites Overview',
            'status.inProgress': 'In Progress',
            'status.delayed': 'Delayed',
            'status.pending': 'Pending',
            'status.completed': 'Completed',
            'users.title': 'User Management',
            'help.title': 'Help & Support',
            'help.description': 'Contact us for any questions or assistance. We are here to help!',
            'help.email': 'Email',
            'help.phone': 'Phone',
            'help.hours': 'Support hours:',
            'help.hoursValue': 'Monday - Friday, 08:00 AM - 06:00 PM',

            // Compte
            'compte.title': 'My Account',
            'compte.tabs.info': 'Personal Information',
            'compte.tabs.subscriptions': 'Subscriptions',
            'compte.tabs.invoices': 'Invoices',
            'compte.form.firstName': 'First Name',
            'compte.form.lastName': 'Last Name',
            'compte.form.phone': 'Phone Number',
            'compte.form.email': 'Email',
            'compte.form.address': 'Address',
            'compte.form.company': 'Company Name',
            'compte.form.profile': 'Profile',
            'compte.profile.cantEdit': 'Profile cannot be modified',
            'compte.photo.new': 'New Photo',
            'compte.photo.reminder': 'Don\'t forget to click "Update" to save your new photo.',
            'compte.subscription.current': 'My Subscription',
            'compte.subscription.expire': 'Expiration Date',
            'compte.subscription.viewOffers': 'View My Offers',
            'compte.subscription.detail': 'Subscription Detail',
            'compte.subscription.planName': 'Plan Name',
            'compte.subscription.subtitle': 'Subtitle',
            'compte.subscription.paymentStatus': 'Payment Status',
            'compte.subscription.paid': 'Paid',
            'compte.subscription.period': 'Period',
            'compte.subscription.amountPaid': 'Amount Paid',
            'compte.subscription.paymentMethod': 'Payment Method',
            'compte.subscription.benefits': 'Included Benefits',
            'compte.subscription.monthly': 'Monthly',
            'compte.subscription.yearly': 'Yearly',
            'compte.subscription.subscribe': 'Subscribe',
            'compte.subscription.upgrade': 'Upgrade to Premium',
            'compte.invoices.search': 'Search here',
            'compte.invoices.allStatus': 'All Statuses',
            'compte.invoices.expired': 'Expired',
            'compte.invoices.table.description': 'Description',
            'compte.invoices.table.period': 'Period',
            'compte.invoices.table.amountHT': 'Amount (Excl. Tax)',
            'compte.save.loading': 'Saving...',

            // Dashboard
            'dashboard.loading.title': 'Loading Dashboard',
            'dashboard.loading.subtitle': 'Analyzing data, please wait...',
            'dashboard.error.title': 'Unable to load data',
            'dashboard.retry': 'Retry',
            'dashboard.searchProject': 'Search by project',
            'dashboard.overview.sites': 'Construction Sites Overview',
            'dashboard.overview.studies': 'Studies Overview',
            'dashboard.studies.distribution': 'Studies Distribution (%)',
            'dashboard.studies.completed': 'Completed',
            'dashboard.studies.initiated': 'Initiated',
            'dashboard.studies.notInitiated': 'Not Initiated',
            'dashboard.indicators.progress': 'Average Progress Rate',
            'dashboard.indicators.budget': 'Global Budget',
            'dashboard.budget.consumed': 'Consumed',
            'dashboard.budget.remaining': 'Remaining',
            'dashboard.alerts.stock': 'Stock Alerts',
            'dashboard.alerts.none': 'No alerts',
            'dashboard.charts.progress': 'Progress Status',
            'dashboard.charts.incidents': 'Reported Incidents (7 days)',
            'dashboard.tasks.critical': 'Critical Tasks Due',
            'dashboard.photos.recent': 'Recent Photos',
            'dashboard.performance.summary': 'Performance Summary',
            'dashboard.performance.avgPresence': 'Average Presence',
            'dashboard.performance.lateTasks': 'Late Tasks',
            'dashboard.performance.alertMaterials': 'Materials in Alert',
            'dashboard.rate.avg': 'Average Rate',
            'dashboard.metrics.inProgress': 'In Progress',
            'dashboard.metrics.delayed': 'Delayed',
            'dashboard.metrics.pending': 'Pending',
            'dashboard.metrics.completed': 'Completed',
            'dashboard.metrics.total': 'Total',
            'dashboard.metrics.delivered': 'Delivered',
            'dashboard.metrics.budgetConsumed': 'Budget Consumed',
            'dashboard.metrics.incidents7d': 'Incidents (7d)',

            // Common / Other
            'common.month.yearly': 'month (yearly)',
            'common.month': 'month',
            'common.year': 'year',
            'common.updateSave': 'Update',
            'common.processing': 'Processing...',
            'common.economize': 'Save',
            'common.unlimitedProjects': 'Unlimited Projects',
            'common.maxProjects': 'project(s) maximum',
            'common.prioritySupport': 'Priority Support',
            'common.installments': 'Payment in {{count}} installments',
            'common.yearlyDiscount': 'discount on yearly payment',
            'common.popular': 'POPULAR',
            'common.changePhoto': 'Change Photo',

            // Generic Section Headers
            'requests.title': 'Requests',
            'orders.title': 'Orders',
            'subscriptions.title': 'Subscriptions',
            'reclamations.title': 'Claims',

            // Users Page
            'users.subtitle': 'Create, edit, view, search, filter registered users',
            'users.table.user': 'User',
            'users.table.registerDate': 'Registration Date',
            'users.create': 'New User',
            'users.deleteConfirm': 'Are you sure you want to delete this user?',

            // Export
            'export.select': 'Export Format',
            'export.excel': 'Export',
            'export.pdf': 'Export to PDF',
            'export.success': 'Export success',
            'export.error': 'Export error',

            // Projects
            'projects.title': 'Ongoing Projects',
            'projects.description': 'View the list of your current construction sites and follow their progress in real time.',
            'projects.newProject': 'New Project',
            'projects.searchByProject': 'Search by project',
            'projects.allPeriods': 'All periods',
            'projects.thisYear': 'This year',
            'projects.lastYear': 'Last year',
            'projects.older': 'Older',
            'projects.allStatuses': 'All statuses',
            'projects.active': 'Active',
            'projects.inactive': 'Inactive',
            'projects.completed': 'Completed',
            'projects.inProgress': 'In progress',
            'projects.progress': 'Progress',
            'projects.loadingProjects': 'Loading projects...',
            'projects.noProjectFound': 'No project found',
            'projects.retry': 'Retry',
            'projects.perPage': 'Projects per page:',
            'projects.page': 'Page',
            'projects.on': 'of',
            'projects.noImage': 'No image',
            'projects.blocked': 'BLOCKED',
            'projects.blockedTitle': 'Blocked Project',
            'projects.blockedRestricted': 'Restricted Access',
            'projects.blockedMessage': 'This project is blocked until your subscription renewal. Please update your plan to access it.',
            'projects.subscriptions': 'Subscriptions',
            'projects.showing': 'Showing',
            'projects.export': 'Export',

            // Project Detail Tabs
            'projectDetail.presentation': 'Presentation',
            'projectDetail.tasks': 'Tasks',
            'projectDetail.team': 'Team',
            'projectDetail.lots': 'Lots',
            'projectDetail.documents': 'Documents',
            'projectDetail.stock': 'Stock',
            'projectDetail.alert': 'Alert',
            'projectDetail.studyBet': 'BET Study',
            'projectDetail.pointingAddress': 'Pointing Address',
            'projectDetail.viewQrCode': 'View QR Code',
            'projectDetail.qrCode': 'QR Code',
            'projectDetail.scanMessage': 'Scan with your phone to open the project details.',
            'projectDetail.project': 'Project',
            'projectDetail.status': 'Status',
            'projectDetail.updateDate': 'Update Date',
            'projectDetail.address': 'Address',
            'projectDetail.print': 'Print',
            'projectDetail.download': 'Download',
            'projectDetail.qrUnavailable': 'QR code unavailable',
            'projectDetail.loading': 'Loading...',
            'projectDetail.selectTab': 'Select a tab',

            // Project Detail - Statuses
            'projectStatus.active': 'Active',
            'projectStatus.inactive': 'Inactive',
            'projectStatus.completed': 'Completed',
            'projectStatus.inProgress': 'In Progress',
            'projectStatus.pending': 'Pending',
            'projectStatus.blocked': 'Blocked',

            // Project Detail - Empty Messages
            'projectDetail.noData': 'No data available',
            'projectDetail.noTasks': 'No tasks',
            'projectDetail.noTeam': 'No team members',
            'projectDetail.noDocuments': 'No documents',
            'projectDetail.noStock': 'No stock',
            'projectDetail.noAlerts': 'No alerts',

            // Project Detail - Confirmations
            'projectDetail.deleteConfirm': 'Are you sure you want to delete?',
            'projectDetail.saveSuccess': 'Saved successfully',
            'projectDetail.saveError': 'Error while saving',

            // Project Detail - Buttons
            'projectDetail.addTask': 'Add Task',
            'projectDetail.addMember': 'Add Member',
            'projectDetail.uploadDocument': 'Upload Document',
            'projectDetail.addStock': 'Add to Stock',
            'projectDetail.reportIssue': 'Report Issue',

            // Dashboard Admin
            'dashboardAdmin.title': 'Administrator Dashboard',
            'dashboardAdmin.users.total': 'Total Users',
            'dashboardAdmin.users.active': 'Active Users',
            'dashboardAdmin.users.pending': 'Pending Validation',
            'dashboardAdmin.projects.total': 'Total Projects',
            'dashboardAdmin.subscriptions.total': 'Total Subscriptions',
            'dashboardAdmin.subscriptions.active': 'Active Subscriptions',
            'dashboardAdmin.subscriptions.expired': 'Expired Subscriptions',
            'dashboardAdmin.revenue.total': 'Cumulative Revenue',
            'dashboardAdmin.revenue.monthly': 'Monthly Revenue',
            'dashboardAdmin.stats': 'Statistics',
            'dashboardAdmin.overview': 'Overview',
            'dashboardAdmin.charts.subscriptions': 'Subscriptions Evolution',
            'dashboardAdmin.charts.revenue': 'Monthly Revenue',
            'dashboardAdmin.charts.profiles': 'Profile Distribution',
            'dashboardAdmin.charts.plans': 'Plan Distribution',
            'dashboardAdmin.invoices.title': 'Latest Paid Invoices',
            'dashboardAdmin.invoices.invoice': 'Invoice',
            'dashboardAdmin.invoices.user': 'User',
            'dashboardAdmin.invoices.plan': 'Plan',
            'dashboardAdmin.invoices.amount': 'Amount',
            'dashboardAdmin.invoices.date': 'Date',
            'dashboardAdmin.invoices.status': 'Status',
            'dashboardAdmin.invoices.paid': 'Paid',
            'dashboardAdmin.invoices.unpaid': 'Unpaid',
            'dashboardAdmin.invoices.noData': 'No invoices available',
            'dashboardAdmin.pagination.showing': 'Showing',
            'dashboardAdmin.pagination.to': 'to',
            'dashboardAdmin.pagination.of': 'of',
            'dashboardAdmin.pagination.results': 'results',
            'dashboardAdmin.pagination.previous': 'Previous',
            'dashboardAdmin.pagination.next': 'Next',

            // Project Presentation
            'projectPresentation.progression': 'Progress',
            'projectPresentation.loadingProgress': 'Loading progress...',
            'projectPresentation.surface': 'Surface',
            'projectPresentation.lots': 'Lots',
            'projectPresentation.startDate': 'Start',
            'projectPresentation.endDate': 'Expected End',
            'projectPresentation.budget': 'Budget',
            'projectPresentation.used': 'Used',
            'projectPresentation.status': 'Status',
            'projectPresentation.updating': 'Updating...',
            'projectPresentation.inProgress': 'In Progress',
            'projectPresentation.paused': 'Paused',
            'projectPresentation.completed': 'Completed',
            'projectPresentation.currentStatus': 'Current Status',
            'projectPresentation.generalInfo': 'General Information',
            'projectPresentation.progressState': 'Progress State',
            'projectPresentation.budgetTab': 'Budget',
            'projectPresentation.add': 'Add',
            'projectPresentation.description': 'Description',
            'projectPresentation.amount': 'Amount',
            'projectPresentation.location': 'Location',
            'projectPresentation.numberOfLots': 'Number of Lots',
            'projectPresentation.dueDate': 'Due Date',
            'projectPresentation.numberOfRooms': 'Number of Rooms',
            'projectPresentation.commonEquipment': 'Common Equipment',
            'projectPresentation.budgetInfo': 'Budget Information',

            // ============ TEAM COMPONENT ============
            'team.searchPlaceholder': 'Search here...',
            'team.filterByRole': 'Filter by role',
            'team.allRoles': 'All roles',
            'team.newMember': 'New member',
            'team.name': 'Name',
            'team.role': 'Role',
            'team.phone': 'Phone',
            'team.present': 'Present',
            'team.action': 'Action',
            'team.loading': 'Loading...',
            'team.retry': 'Retry',
            'team.yes': 'Yes',
            'team.no': 'No',
            'team.noMembers': 'No team members found',
            'team.startAddingMembers': 'Start by adding members to your team',
            'team.previous': 'Previous',
            'team.next': 'Next',
            'team.addNewMember': 'Add a new member',
            'team.lastName': 'Last Name',
            'team.firstName': 'First Name',
            'team.email': 'Email',
            'team.birthDate': 'Birth Date',
            'team.birthPlace': 'Birth Place',
            'team.address': 'Address',
            'team.profilePhoto': 'Profile Photo',
            'team.password': 'Password',
            'team.cancel': 'Cancel',
            'team.add': 'Add',
            'team.adding': 'Adding...',
            'team.details': 'Details',
            'team.daysPresent': 'Days Present',
            'team.hoursWorked': 'Hours Worked',
            'team.tasksCompleted': 'Tasks Completed',
            'team.performance': 'Performance',
            'team.taskDistribution': 'Task Distribution (%)',
            'team.toDo': 'To Do',
            'team.inProgress': 'In Progress',
            'team.completed': 'Completed',
            'team.late': 'Late',
            'team.presenceHistory': 'Presence History',
            'team.filterByDate': 'Filter by date',
            'team.entry': 'Entry',
            'team.exit': 'Exit',
            'team.total': 'Total',
            'team.noPresenceHistory': 'No presence history available',
            'team.totalHoursWorked': 'Total Hours Worked',
            'team.close': 'Close',
            'team.worker': 'Worker',
            'team.acceptedFormats': 'Accepted formats: JPG, PNG, GIF (Max 5MB)',
            'team.passwordMinLength': 'Password (minimum 6 characters)',

            // ============ DOCUMENTS COMPONENT ============
            'documents.title': 'Documents',
            'documents.search': 'Search for a document...',
            'documents.addDocument': 'Add document',
            'documents.name': 'Name',
            'documents.type': 'Type',
            'documents.size': 'Size',
            'documents.date': 'Date',
            'documents.actions': 'Actions',
            'documents.download': 'Download',
            'documents.delete': 'Delete',
            'documents.view': 'View',
            'documents.noDocuments': 'No documents found',
            'documents.uploadDocument': 'Upload a document',
            'documents.dragDrop': 'Drag and drop your files here',
            'documents.or': 'or',
            'documents.browse': 'Browse',
            'documents.cancel': 'Cancel',
            'documents.upload': 'Upload',
            'documents.uploading': 'Uploading...',
            'documents.deleteConfirm': 'Are you sure you want to delete this document?',
            'documents.confirmDelete': 'Confirm deletion',
            'documents.category': 'Category',
            'documents.allCategories': 'All categories',
            'documents.administrative': 'Administrative',
            'documents.technical': 'Technical',
            'documents.financial': 'Financial',
            'documents.other': 'Other',

            // ============ STOCK COMPONENT ============
            'stock.title': 'Stock',
            'stock.search': 'Search for an item...',
            'stock.addArticle': 'Add item',
            'stock.articleName': 'Item name',
            'stock.category': 'Category',
            'stock.quantity': 'Quantity',
            'stock.unit': 'Unit',
            'stock.minStock': 'Minimum stock',
            'stock.currentStock': 'Current stock',
            'stock.status': 'Status',
            'stock.actions': 'Actions',
            'stock.inStock': 'In stock',
            'stock.lowStock': 'Low stock',
            'stock.outOfStock': 'Out of stock',
            'stock.edit': 'Edit',
            'stock.delete': 'Delete',
            'stock.noArticles': 'No items in stock',
            'stock.addNewArticle': 'Add a new item',
            'stock.editArticle': 'Edit item',
            'stock.cancel': 'Cancel',
            'stock.save': 'Save',
            'stock.saving': 'Saving...',
            'stock.deleteConfirm': 'Are you sure you want to delete this item?',
            'stock.confirmDelete': 'Confirm deletion',
            'stock.allCategories': 'All categories',
            'stock.materials': 'Materials',
            'stock.tools': 'Tools',
            'stock.equipment': 'Equipment',
            'stock.consumables': 'Consumables',
            'stock.supplier': 'Supplier',
            'stock.unitPrice': 'Unit price',
            'stock.totalValue': 'Total value',
            'stock.lastUpdated': 'Last updated',
            'stock.addStock': 'Add stock',
            'stock.removeStock': 'Remove stock',
            'stock.movement': 'Movement',
            'stock.movementHistory': 'Movement history',

            // ============ LOTS COMPONENT ============
            'lots.title': 'Lots',
            'lots.search': 'Search for a lot...',
            'lots.addLot': 'Add lot',
            'lots.lotNumber': 'Lot number',
            'lots.lotName': 'Lot name',
            'lots.description': 'Description',
            'lots.subcontractor': 'Subcontractor',
            'lots.budget': 'Budget',
            'lots.progress': 'Progress',
            'lots.status': 'Status',
            'lots.actions': 'Actions',
            'lots.notStarted': 'Not started',
            'lots.inProgress': 'In progress',
            'lots.completed': 'Completed',
            'lots.suspended': 'Suspended',
            'lots.noLots': 'No lots found',
            'lots.addNewLot': 'Add a new lot',
            'lots.editLot': 'Edit lot',
            'lots.cancel': 'Cancel',
            'lots.save': 'Save',
            'lots.saving': 'Saving...',
            'lots.deleteConfirm': 'Are you sure you want to delete this lot?',
            'lots.confirmDelete': 'Confirm deletion',
            'lots.assignSubcontractor': 'Assign subcontractor',
            'lots.selectSubcontractor': 'Select a subcontractor',
            'lots.noSubcontractor': 'No subcontractor assigned',
            'lots.startDate': 'Start date',
            'lots.endDate': 'End date',
            'lots.estimatedBudget': 'Estimated budget',
            'lots.actualBudget': 'Actual budget',
            'lots.view': 'View',
            'lots.edit': 'Edit',
            'lots.delete': 'Delete',

            // ============ ALERT/SIGNALEMENT COMPONENT ============
            'alert.title': 'Alerts',
            'alert.search': 'Search for an alert...',
            'alert.addAlert': 'New alert',
            'alert.alertType': 'Alert type',
            'alert.priority': 'Priority',
            'alert.status': 'Status',
            'alert.date': 'Date',
            'alert.reportedBy': 'Reported by',
            'alert.description': 'Description',
            'alert.actions': 'Actions',
            'alert.high': 'High',
            'alert.medium': 'Medium',
            'alert.low': 'Low',
            'alert.open': 'Open',
            'alert.inProgress': 'In progress',
            'alert.resolved': 'Resolved',
            'alert.closed': 'Closed',
            'alert.noAlerts': 'No alerts',
            'alert.addNewAlert': 'Add an alert',
            'alert.editAlert': 'Edit alert',
            'alert.cancel': 'Cancel',
            'alert.save': 'Save',
            'alert.saving': 'Saving...',
            'alert.deleteConfirm': 'Are you sure you want to delete this alert?',
            'alert.confirmDelete': 'Confirm deletion',
            'alert.safety': 'Safety',
            'alert.quality': 'Quality',
            'alert.delay': 'Delay',
            'alert.material': 'Material',
            'alert.other': 'Other',
            'alert.location': 'Location',
            'alert.photos': 'Photos',
            'alert.addPhotos': 'Add photos',
            'alert.view': 'View',
            'alert.edit': 'Edit',
            'alert.delete': 'Delete',
            'alert.resolve': 'Resolve',
            'alert.reopen': 'Reopen',
            'alert.allTypes': 'All types',
            'alert.allPriorities': 'All priorities',
            'alert.allStatuses': 'All statuses',

            // ============ STUDY BET COMPONENT ============
            'studyBet.title': 'Technical Studies',
            'studyBet.search': 'Search for a study...',
            'studyBet.addStudy': 'New study',
            'studyBet.studyName': 'Study name',
            'studyBet.studyType': 'Study type',
            'studyBet.office': 'Technical office',
            'studyBet.status': 'Status',
            'studyBet.deliveryDate': 'Delivery date',
            'studyBet.actions': 'Actions',
            'studyBet.pending': 'Pending',
            'studyBet.inProgress': 'In progress',
            'studyBet.delivered': 'Delivered',
            'studyBet.validated': 'Validated',
            'studyBet.rejected': 'Rejected',
            'studyBet.noStudies': 'No studies found',
            'studyBet.addNewStudy': 'Add a study',
            'studyBet.editStudy': 'Edit study',
            'studyBet.cancel': 'Cancel',
            'studyBet.save': 'Save',
            'studyBet.saving': 'Saving...',
            'studyBet.deleteConfirm': 'Are you sure you want to delete this study?',
            'studyBet.confirmDelete': 'Confirm deletion',
            'studyBet.structural': 'Structural',
            'studyBet.electrical': 'Electrical',
            'studyBet.plumbing': 'Plumbing',
            'studyBet.hvac': 'HVAC',
            'studyBet.architectural': 'Architectural',
            'studyBet.geotechnical': 'Geotechnical',
            'studyBet.other': 'Other',
            'studyBet.documents': 'Documents',
            'studyBet.comments': 'Comments',
            'studyBet.version': 'Version',
            'studyBet.view': 'View',
            'studyBet.edit': 'Edit',
            'studyBet.delete': 'Delete',
            'studyBet.validate': 'Validate',
            'studyBet.reject': 'Reject',
            'studyBet.download': 'Download',

            // ============ POINTING ADDRESS COMPONENT ============
            'pointingAddress.title': 'Check-in Address',
            'pointingAddress.search': 'Search...',
            'pointingAddress.addAddress': 'Add address',
            'pointingAddress.addressName': 'Address name',
            'pointingAddress.fullAddress': 'Full address',
            'pointingAddress.latitude': 'Latitude',
            'pointingAddress.longitude': 'Longitude',
            'pointingAddress.radius': 'Radius (meters)',
            'pointingAddress.status': 'Status',
            'pointingAddress.actions': 'Actions',
            'pointingAddress.active': 'Active',
            'pointingAddress.inactive': 'Inactive',
            'pointingAddress.noAddresses': 'No check-in addresses',
            'pointingAddress.addNewAddress': 'Add a check-in address',
            'pointingAddress.editAddress': 'Edit address',
            'pointingAddress.cancel': 'Cancel',
            'pointingAddress.save': 'Save',
            'pointingAddress.saving': 'Saving...',
            'pointingAddress.deleteConfirm': 'Are you sure you want to delete this address?',
            'pointingAddress.confirmDelete': 'Confirm deletion',
            'pointingAddress.selectOnMap': 'Select on map',
            'pointingAddress.currentLocation': 'Current location',
            'pointingAddress.view': 'View',
            'pointingAddress.edit': 'Edit',
            'pointingAddress.delete': 'Delete',
            'pointingAddress.activate': 'Activate',
            'pointingAddress.deactivate': 'Deactivate',

            // ============ STATUS REPORT/ALBUMS COMPONENT ============
            'statusReport.albumsView': 'Albums View',
            'statusReport.graphView': 'Graph View',
            'statusReport.indicatorsTable': 'Indicators Table',
            'statusReport.viewPhotos': 'View photos',
            'statusReport.editAlbum': 'Edit album',
            'statusReport.deleteAlbum': 'Delete album',
            'statusReport.photos': 'photos',
            'statusReport.step': 'Step',
            'statusReport.percentage': '%Percentage',
            'statusReport.updateDate': 'Update Date',
            'statusReport.selectPercentage': 'Select a percentage',
            'statusReport.close': 'Close',
            'statusReport.createAlbum': 'Create a new album',
            'statusReport.albumName': 'Album name',
            'statusReport.description': 'Description',
            'statusReport.albumPhotos': 'Album photos',
            'statusReport.clickToAdd': 'Click to add photos or drag and drop',
            'statusReport.acceptedFormats': 'PNG, JPG, JPEG up to 10MB',
            'statusReport.selectedPhotos': 'Selected photos',
            'statusReport.cancel': 'Cancel',
            'statusReport.create': 'Create',
            'statusReport.modify': 'Modify',
            'statusReport.currentPhotos': 'Current photos',
            'statusReport.addNewPhotos': 'Add new photos',
            'statusReport.confirmDeletion': 'Confirm deletion',
            'statusReport.deleteConfirmMessage': 'Are you sure you want to delete the album',
            'statusReport.irreversibleAction': 'This action is irreversible.',
            'statusReport.noCancel': 'No, cancel',
            'statusReport.yesDelete': 'Yes, delete',
            'statusReport.noPhotos': 'No photos in this album',

            // Logout Confirmation
            'logout.confirmTitle': 'Confirm Logout',
            'logout.confirmMessage': 'Are you sure you want to log out?',
            'logout.confirm': 'Log Out',
        }
    };

    constructor() {
        const savedLang = localStorage.getItem('language') as Language;
        if (savedLang && (savedLang === 'FR' || savedLang === 'EN')) {
            this.currentLang.set(savedLang);
        }
    }

    changeLanguage(lang: Language) {
        this.currentLang.set(lang);
        localStorage.setItem('language', lang);
    }

    translate(key: string, params?: { [key: string]: string | number }): string {
        const lang = this.currentLang();
        let text = this.translations[lang][key] || key;

        if (params) {
            Object.keys(params).forEach(param => {
                text = text.replace(`{{${param}}}`, String(params[param]));
            });
        }

        return text;
    }
}
